### ISSUE TITLE
Feature request: Disable scroll wheel zoom on property editor

### ISSUE THREAD

**Issue by creativesuspects** [bergmania/Bergmania.OpenStreetMap#20]
I love using OpenStreetMap, so thanks for this package! It would be nice if the data type had a setting to disable the scroll wheel zoom (`scrollWheelZoom: false`). Often when editors scroll through the list of properties on a document type and the cursor hits the map they start zooming out on the map instead of scrolling further down the list.

In this example there are no properties below the map, but you get the idea:
https://user-images.githubusercontent.com/161342/201069954-00ee7205-191f-489b-a81b-ca41711cc874.mp4

**Comment by bergmania** [comment]
Makes good sense.. Feel free to add such a feature :)

**Comment by creativesuspects** [comment]
Working on a PR...

**Comment by creativesuspects** [comment]
Hi Bjarke! Please check out my PR. I hope you can publish a new NuGet package version soon.
