### ISSUE TITLE
Map doesn't render correct inside tab

### ISSUE THREAD

**Issue by bjarnef** [bergmania/Bergmania.OpenStreetMap#25]
It seems the map isn't rendered as expected inside a tab in latest Umbraco version.

If map is under first tab I can find a location and after refresh it is also shown like this:

![image](https://github.com/bergmania/Bergmania.OpenStreetMap/assets/2919859/d5da2b3b-32f2-4fb3-8163-6bd498753202)

If I then re-order "Map" tab to third tab and go back I see this:

![image](https://github.com/bergmania/Bergmania.OpenStreetMap/assets/2919859/d9719030-6184-4bde-981d-7ad8f843e7b0)

if I search same location again here and hit save and publish, I get this:

![image](https://github.com/bergmania/Bergmania.OpenStreetMap/assets/2919859/993a307e-138a-4474-a6f4-8288850695ba)

if I then re-order "Map" tab to first tab again and go back, I get this:

![image](https://github.com/bergmania/Bergmania.OpenStreetMap/assets/2919859/94677bd6-889d-4d01-9680-819245ce3a15)

but searching the location once again, it is updated this this:

![image](https://github.com/bergmania/Bergmania.OpenStreetMap/assets/2919859/46859c98-3782-4ff2-b076-60a880f09b95)

Bergmania.OpenStreetMap 5.3.0
Umbraco.Cms 11.4.1

**Comment by bergmania** [comment]
Thanks for reporting.. Should be fixed in 5.3.1
